/* Generated by Yosys 0.63 (git sha1 70a11c6bf, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "uart_top" *)
(* top =  1  *)
(* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_top.v:3.1-68.10" *)
module uart_top(clk, rst_n, tx_start, tx_data, rx_data, rx_done, tx_busy);
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_top.v:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_top.v:6.11-6.16" *)
  input rst_n;
  wire rst_n;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_top.v:7.11-7.19" *)
  input tx_start;
  wire tx_start;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_top.v:8.17-8.24" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_top.v:10.18-10.25" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_top.v:11.12-11.19" *)
  output rx_done;
  wire rx_done;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_top.v:12.12-12.19" *)
  output tx_busy;
  wire tx_busy;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _009_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _010_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _011_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _012_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _013_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _014_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _015_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _016_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _017_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _018_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _019_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _020_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _021_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _022_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _023_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  wire _024_;
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  wire _025_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _026_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:6.28-6.29" *)
  wire _027_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _028_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _029_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _030_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:6.28-6.29" *)
  wire _031_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _032_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _033_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _034_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _035_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _036_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:6.25-6.26" *)
  wire _037_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:6.28-6.29" *)
  wire _038_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _039_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _040_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _041_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _150_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  (* unused_bits = "0" *)
  wire _151_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  (* unused_bits = "0" *)
  wire _152_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  (* unused_bits = "0" *)
  wire _153_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  (* unused_bits = "0" *)
  wire _154_;
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  (* unused_bits = "0" *)
  wire _155_;
  (* hdlname = "BAUD_GEN baud_tick" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:5.16-5.25" *)
  wire \BAUD_GEN.baud_tick ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[0] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[10] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[11] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[12] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[13] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[1] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[2] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[3] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[4] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[5] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[6] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[7] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[8] ;
  (* hdlname = "BAUD_GEN count" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:8.12-8.17" *)
  wire \BAUD_GEN.count[9] ;
  (* hdlname = "BAUD_GEN half_baud" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:5.27-5.36" *)
  wire \BAUD_GEN.half_baud ;
  (* hdlname = "UART_RX bit_index" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:10.11-10.20" *)
  wire \UART_RX.bit_index[0] ;
  (* hdlname = "UART_RX bit_index" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:10.11-10.20" *)
  wire \UART_RX.bit_index[1] ;
  (* hdlname = "UART_RX bit_index" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:10.11-10.20" *)
  wire \UART_RX.bit_index[2] ;
  (* hdlname = "UART_RX first_tick" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:14.5-14.15" *)
  wire \UART_RX.first_tick ;
  (* hdlname = "UART_RX rx" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:4.34-4.36" *)
  wire \UART_RX.rx ;
  (* hdlname = "UART_RX rx_prev" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:13.5-13.12" *)
  wire \UART_RX.rx_prev ;
  (* hdlname = "UART_RX rx_sync1" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:11.5-11.13" *)
  wire \UART_RX.rx_sync1 ;
  (* hdlname = "UART_RX rx_sync2" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:12.5-12.13" *)
  wire \UART_RX.rx_sync2 ;
  wire \UART_RX.state[0] ;
  wire \UART_RX.state[1] ;
  wire \UART_RX.state[2] ;
  wire \UART_RX.state[3] ;
  (* hdlname = "UART_TX bit_index" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:10.11-10.20" *)
  wire \UART_TX.bit_index[0] ;
  (* hdlname = "UART_TX bit_index" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:10.11-10.20" *)
  wire \UART_TX.bit_index[1] ;
  (* hdlname = "UART_TX bit_index" *)
  (* init = 1'b0 *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:10.11-10.20" *)
  wire \UART_TX.bit_index[2] ;
  (* hdlname = "UART_TX data_reg" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:11.11-11.19" *)
  wire \UART_TX.data_reg[0] ;
  (* hdlname = "UART_TX data_reg" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:11.11-11.19" *)
  wire \UART_TX.data_reg[1] ;
  (* hdlname = "UART_TX data_reg" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:11.11-11.19" *)
  wire \UART_TX.data_reg[2] ;
  (* hdlname = "UART_TX data_reg" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:11.11-11.19" *)
  wire \UART_TX.data_reg[3] ;
  (* hdlname = "UART_TX data_reg" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:11.11-11.19" *)
  wire \UART_TX.data_reg[4] ;
  (* hdlname = "UART_TX data_reg" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:11.11-11.19" *)
  wire \UART_TX.data_reg[5] ;
  (* hdlname = "UART_TX data_reg" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:11.11-11.19" *)
  wire \UART_TX.data_reg[6] ;
  (* hdlname = "UART_TX data_reg" *)
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:11.11-11.19" *)
  wire \UART_TX.data_reg[7] ;
  wire \UART_TX.state[0] ;
  wire \UART_TX.state[1] ;
  wire \UART_TX.state[2] ;
  wire \UART_TX.state[3] ;
  sky130_fd_sc_hd__inv_1 _156_ (
    .A(\BAUD_GEN.count[1] ),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_1 _157_ (
    .A(\UART_RX.bit_index[1] ),
    .Y(_038_)
  );
  sky130_fd_sc_hd__inv_1 _158_ (
    .A(\UART_RX.bit_index[0] ),
    .Y(_037_)
  );
  sky130_fd_sc_hd__and2_1 _159_ (
    .A(\BAUD_GEN.count[4] ),
    .B(\BAUD_GEN.count[5] ),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _160_ (
    .A(\BAUD_GEN.count[11] ),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _161_ (
    .A(\BAUD_GEN.count[10] ),
    .B(\BAUD_GEN.count[6] ),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand3_1 _162_ (
    .A(_028_),
    .B(\BAUD_GEN.count[13] ),
    .C(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor3_1 _163_ (
    .A(\BAUD_GEN.count[9] ),
    .B(\BAUD_GEN.count[8] ),
    .C(\BAUD_GEN.count[3] ),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _164_ (
    .A(\BAUD_GEN.count[2] ),
    .B(\BAUD_GEN.count[12] ),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand3_1 _165_ (
    .A(\BAUD_GEN.count[7] ),
    .B(_064_),
    .C(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor3_2 _166_ (
    .A(_061_),
    .B(_063_),
    .C(_066_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _167_ (
    .A(\BAUD_GEN.count[4] ),
    .B(\BAUD_GEN.count[5] ),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand3_1 _168_ (
    .A(\BAUD_GEN.count[2] ),
    .B(\BAUD_GEN.count[3] ),
    .C(_030_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _169_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__and4_1 _170_ (
    .A(\BAUD_GEN.count[9] ),
    .B(\BAUD_GEN.count[8] ),
    .C(\BAUD_GEN.count[6] ),
    .D(\BAUD_GEN.count[7] ),
    .X(_070_)
  );
  sky130_fd_sc_hd__nand4_1 _171_ (
    .A(\BAUD_GEN.count[11] ),
    .B(\BAUD_GEN.count[10] ),
    .C(_069_),
    .D(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xnor2_1 _172_ (
    .A(\BAUD_GEN.count[12] ),
    .B(_071_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__and4_1 _173_ (
    .A(\BAUD_GEN.count[1] ),
    .B(\BAUD_GEN.count[2] ),
    .C(\BAUD_GEN.count[3] ),
    .D(\BAUD_GEN.count[0] ),
    .X(_072_)
  );
  sky130_fd_sc_hd__nand4_1 _174_ (
    .A(\BAUD_GEN.count[10] ),
    .B(_060_),
    .C(_070_),
    .D(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__xor2_1 _175_ (
    .A(\BAUD_GEN.count[11] ),
    .B(_073_),
    .X(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _176_ (
    .A(_009_),
    .B(_074_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _177_ (
    .A(_069_),
    .B(_070_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(\BAUD_GEN.count[10] ),
    .B(_075_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__and3_1 _179_ (
    .A(\BAUD_GEN.count[8] ),
    .B(\BAUD_GEN.count[6] ),
    .C(\BAUD_GEN.count[7] ),
    .X(_076_)
  );
  sky130_fd_sc_hd__nand3_1 _180_ (
    .A(_060_),
    .B(_076_),
    .C(_072_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__xnor2_1 _181_ (
    .A(\BAUD_GEN.count[9] ),
    .B(_077_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__and3_1 _182_ (
    .A(\BAUD_GEN.count[6] ),
    .B(\BAUD_GEN.count[7] ),
    .C(_069_),
    .X(_078_)
  );
  sky130_fd_sc_hd__xor2_1 _183_ (
    .A(\BAUD_GEN.count[8] ),
    .B(_078_),
    .X(_022_)
  );
  sky130_fd_sc_hd__nand3_1 _184_ (
    .A(\BAUD_GEN.count[6] ),
    .B(_060_),
    .C(_072_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__xor2_1 _185_ (
    .A(\BAUD_GEN.count[7] ),
    .B(_079_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(_009_),
    .B(_080_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xor2_1 _187_ (
    .A(\BAUD_GEN.count[6] ),
    .B(_069_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(\BAUD_GEN.count[4] ),
    .B(_072_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__xor2_1 _189_ (
    .A(\BAUD_GEN.count[5] ),
    .B(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _190_ (
    .A(_009_),
    .B(_082_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _191_ (
    .A(\BAUD_GEN.count[4] ),
    .B(_068_),
    .X(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _192_ (
    .A(_009_),
    .B(_083_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand3_1 _193_ (
    .A(\BAUD_GEN.count[1] ),
    .B(\BAUD_GEN.count[2] ),
    .C(\BAUD_GEN.count[0] ),
    .Y(_084_)
  );
  sky130_fd_sc_hd__xnor2_1 _194_ (
    .A(\BAUD_GEN.count[3] ),
    .B(_084_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _195_ (
    .A(\BAUD_GEN.count[2] ),
    .B(_030_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor2_1 _196_ (
    .A(_009_),
    .B(_085_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(_029_),
    .B(_009_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _198_ (
    .A(\BAUD_GEN.count[0] ),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkbuf_1 _199_ (
    .A(\BAUD_GEN.baud_tick ),
    .X(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _200_ (
    .A(_086_),
    .B(tx_start),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a22o_1 _201_ (
    .A1(\UART_TX.state[3] ),
    .A2(_086_),
    .B1(_087_),
    .B2(\UART_TX.state[0] ),
    .X(_000_)
  );
  sky130_fd_sc_hd__clkbuf_1 _202_ (
    .A(\BAUD_GEN.baud_tick ),
    .X(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(_035_),
    .B(_086_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a22o_1 _204_ (
    .A1(_088_),
    .A2(\UART_TX.state[2] ),
    .B1(_089_),
    .B2(\UART_TX.state[1] ),
    .X(_001_)
  );
  sky130_fd_sc_hd__inv_1 _205_ (
    .A(\UART_TX.state[2] ),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand3_1 _206_ (
    .A(\UART_TX.state[0] ),
    .B(_088_),
    .C(tx_start),
    .Y(_091_)
  );
  sky130_fd_sc_hd__o21ai_1 _207_ (
    .A1(_088_),
    .A2(_090_),
    .B1(_091_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__inv_1 _208_ (
    .A(\UART_TX.state[3] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand3_1 _209_ (
    .A(\UART_TX.state[1] ),
    .B(_035_),
    .C(_088_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21ai_0 _210_ (
    .A1(_092_),
    .A2(_088_),
    .B1(_093_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2b_1 _211_ (
    .A_N(\UART_RX.rx_sync2 ),
    .B(\UART_RX.rx_prev ),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a22o_2 _212_ (
    .A1(_086_),
    .A2(\UART_RX.state[3] ),
    .B1(_094_),
    .B2(\UART_RX.state[0] ),
    .X(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(\BAUD_GEN.half_baud ),
    .B(\UART_RX.state[2] ),
    .Y(_095_)
  );
  sky130_fd_sc_hd__inv_1 _214_ (
    .A(_034_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__or2b_1 _215_ (
    .A(\UART_RX.first_tick ),
    .B_N(\BAUD_GEN.baud_tick ),
    .X(_097_)
  );
  sky130_fd_sc_hd__clkbuf_1 _216_ (
    .A(\UART_RX.state[1] ),
    .X(_098_)
  );
  sky130_fd_sc_hd__o21ai_1 _217_ (
    .A1(_096_),
    .A2(_097_),
    .B1(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(_095_),
    .B(_099_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_1 _219_ (
    .A(\UART_RX.state[0] ),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2b_1 _220_ (
    .A_N(\BAUD_GEN.half_baud ),
    .B(\UART_RX.state[2] ),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o21ai_0 _221_ (
    .A1(_100_),
    .A2(_094_),
    .B1(_101_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_1 _222_ (
    .A(\UART_RX.state[3] ),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2b_1 _223_ (
    .A(\UART_RX.first_tick ),
    .B_N(\BAUD_GEN.baud_tick ),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand3_1 _224_ (
    .A(_098_),
    .B(_032_),
    .C(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21ai_0 _225_ (
    .A1(_088_),
    .A2(_102_),
    .B1(_104_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__and3_1 _226_ (
    .A(_088_),
    .B(\UART_TX.state[2] ),
    .C(rst_n),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor4bb_1 _227_ (
    .A(\BAUD_GEN.count[7] ),
    .B(\BAUD_GEN.count[5] ),
    .C_N(\BAUD_GEN.count[4] ),
    .D_N(\BAUD_GEN.count[6] ),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _228_ (
    .A(_064_),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor4bb_1 _229_ (
    .A(\BAUD_GEN.count[11] ),
    .B(\BAUD_GEN.count[13] ),
    .C_N(\BAUD_GEN.count[12] ),
    .D_N(\BAUD_GEN.count[10] ),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand3_1 _230_ (
    .A(\BAUD_GEN.count[2] ),
    .B(_030_),
    .C(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor2_1 _231_ (
    .A(_106_),
    .B(_108_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__and4_1 _232_ (
    .A(\BAUD_GEN.count[11] ),
    .B(\BAUD_GEN.count[4] ),
    .C(\BAUD_GEN.count[5] ),
    .D(\BAUD_GEN.count[12] ),
    .X(_109_)
  );
  sky130_fd_sc_hd__nand4_1 _233_ (
    .A(\BAUD_GEN.count[10] ),
    .B(_070_),
    .C(_072_),
    .D(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xor2_1 _234_ (
    .A(\BAUD_GEN.count[13] ),
    .B(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(_009_),
    .B(_111_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and3_1 _236_ (
    .A(\UART_RX.rx_sync2 ),
    .B(_088_),
    .C(\UART_RX.state[3] ),
    .X(_025_)
  );
  sky130_fd_sc_hd__nand3_1 _237_ (
    .A(_037_),
    .B(_098_),
    .C(_096_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__o21ai_0 _238_ (
    .A1(_098_),
    .A2(\UART_RX.state[2] ),
    .B1(_101_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a21oi_1 _239_ (
    .A1(_098_),
    .A2(_097_),
    .B1(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__mux2i_1 _240_ (
    .A0(_037_),
    .A1(_112_),
    .S(_114_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__or3_4 _241_ (
    .A(\UART_RX.state[0] ),
    .B(\UART_RX.state[3] ),
    .C(\UART_RX.state[2] ),
    .X(_115_)
  );
  sky130_fd_sc_hd__xnor2_1 _242_ (
    .A(_039_),
    .B(\UART_RX.bit_index[2] ),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a211oi_4 _243_ (
    .A1(_098_),
    .A2(_097_),
    .B1(_115_),
    .C1(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _244_ (
    .A(_041_),
    .B(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _245_ (
    .A(\UART_RX.bit_index[1] ),
    .B(\UART_RX.bit_index[2] ),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(\UART_RX.rx_sync2 ),
    .B(_040_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor3_1 _247_ (
    .A(\UART_RX.bit_index[0] ),
    .B(_119_),
    .C(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a22o_1 _248_ (
    .A1(rx_data[6]),
    .A2(_118_),
    .B1(_121_),
    .B2(_117_),
    .X(_044_)
  );
  sky130_fd_sc_hd__a21boi_1 _249_ (
    .A1(_042_),
    .A2(_117_),
    .B1_N(rx_data[5]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a41o_1 _250_ (
    .A1(\UART_RX.bit_index[0] ),
    .A2(\UART_RX.rx_sync2 ),
    .A3(_040_),
    .A4(_117_),
    .B1(_122_),
    .X(_045_)
  );
  sky130_fd_sc_hd__xor2_1 _251_ (
    .A(_039_),
    .B(\UART_RX.bit_index[2] ),
    .X(_123_)
  );
  sky130_fd_sc_hd__a211oi_4 _252_ (
    .A1(_098_),
    .A2(_097_),
    .B1(_115_),
    .C1(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(\UART_RX.bit_index[0] ),
    .B(_040_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand3b_2 _254_ (
    .A_N(_119_),
    .B(_124_),
    .C(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__mux2_4 _255_ (
    .A0(\UART_RX.rx_sync2 ),
    .A1(rx_data[4]),
    .S(_126_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(_031_),
    .B(_124_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(\UART_RX.bit_index[0] ),
    .B(\UART_RX.rx_sync2 ),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor2_1 _258_ (
    .A(_040_),
    .B(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a22o_1 _259_ (
    .A1(rx_data[3]),
    .A2(_127_),
    .B1(_129_),
    .B2(_124_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(_041_),
    .B(_124_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a22o_1 _261_ (
    .A1(_121_),
    .A2(_124_),
    .B1(_130_),
    .B2(rx_data[2]),
    .X(_048_)
  );
  sky130_fd_sc_hd__a21boi_1 _262_ (
    .A1(_042_),
    .A2(_124_),
    .B1_N(rx_data[1]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a41o_1 _263_ (
    .A1(\UART_RX.bit_index[0] ),
    .A2(\UART_RX.rx_sync2 ),
    .A3(_040_),
    .A4(_124_),
    .B1(_131_),
    .X(_049_)
  );
  sky130_fd_sc_hd__o21ai_0 _264_ (
    .A1(\UART_TX.state[1] ),
    .A2(\UART_TX.state[2] ),
    .B1(_086_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a32o_1 _265_ (
    .A1(_036_),
    .A2(\UART_TX.state[1] ),
    .A3(_086_),
    .B1(_132_),
    .B2(\UART_TX.bit_index[2] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__inv_1 _266_ (
    .A(\UART_RX.bit_index[2] ),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand4_1 _267_ (
    .A(_098_),
    .B(_033_),
    .C(_103_),
    .D(_101_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21ai_0 _268_ (
    .A1(_133_),
    .A2(_114_),
    .B1(_134_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _269_ (
    .A1(\BAUD_GEN.half_baud ),
    .A2(\UART_RX.state[2] ),
    .B1(\UART_RX.first_tick ),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(_086_),
    .B(_101_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(\UART_RX.first_tick ),
    .B(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o21ai_1 _272_ (
    .A1(_098_),
    .A2(_135_),
    .B1(_137_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o21ai_0 _273_ (
    .A1(\UART_TX.state[3] ),
    .A2(\UART_TX.state[0] ),
    .B1(_086_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__inv_1 _274_ (
    .A(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _275_ (
    .A1(_088_),
    .A2(\UART_TX.state[2] ),
    .B1(tx_busy),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(_139_),
    .B(_140_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand3_2 _277_ (
    .A(_117_),
    .B(_119_),
    .C(_125_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__mux2_1 _278_ (
    .A0(\UART_RX.rx_sync2 ),
    .A1(rx_data[0]),
    .S(_141_),
    .X(_054_)
  );
  sky130_fd_sc_hd__inv_1 _279_ (
    .A(\UART_RX.rx ),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _280_ (
    .A(\UART_TX.state[1] ),
    .B(_086_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__mux4_2 _281_ (
    .A0(\UART_TX.data_reg[0] ),
    .A1(\UART_TX.data_reg[1] ),
    .A2(\UART_TX.data_reg[2] ),
    .A3(\UART_TX.data_reg[3] ),
    .S0(\UART_TX.bit_index[0] ),
    .S1(\UART_TX.bit_index[1] ),
    .X(_144_)
  );
  sky130_fd_sc_hd__mux4_2 _282_ (
    .A0(\UART_TX.data_reg[4] ),
    .A1(\UART_TX.data_reg[5] ),
    .A2(\UART_TX.data_reg[6] ),
    .A3(\UART_TX.data_reg[7] ),
    .S0(\UART_TX.bit_index[0] ),
    .S1(\UART_TX.bit_index[1] ),
    .X(_145_)
  );
  sky130_fd_sc_hd__mux2i_1 _283_ (
    .A0(_144_),
    .A1(_145_),
    .S(\UART_TX.bit_index[2] ),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o221ai_1 _284_ (
    .A1(_088_),
    .A2(_142_),
    .B1(_143_),
    .B2(_146_),
    .C1(_138_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(_031_),
    .B(_117_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a22o_1 _286_ (
    .A1(_117_),
    .A2(_129_),
    .B1(_147_),
    .B2(rx_data[7]),
    .X(_056_)
  );
  sky130_fd_sc_hd__a32o_1 _287_ (
    .A1(_026_),
    .A2(\UART_TX.state[1] ),
    .A3(_086_),
    .B1(_132_),
    .B2(\UART_TX.bit_index[1] ),
    .X(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _288_ (
    .A(\UART_TX.bit_index[0] ),
    .B(_132_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o31ai_1 _289_ (
    .A1(_035_),
    .A2(\UART_TX.bit_index[0] ),
    .A3(_143_),
    .B1(_148_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand3b_1 _290_ (
    .A_N(_032_),
    .B(_098_),
    .C(_040_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__mux2i_1 _291_ (
    .A0(_038_),
    .A1(_149_),
    .S(_114_),
    .Y(_059_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _292_ (
    .A(\UART_TX.bit_index[0] ),
    .B(\UART_TX.bit_index[1] ),
    .COUT(_150_),
    .SUM(_026_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _293_ (
    .A(\BAUD_GEN.count[0] ),
    .B(_027_),
    .COUT(_028_),
    .SUM(_029_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _294_ (
    .A(\BAUD_GEN.count[0] ),
    .B(\BAUD_GEN.count[1] ),
    .COUT(_030_),
    .SUM(_151_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _295_ (
    .A(\UART_RX.bit_index[2] ),
    .B(_031_),
    .COUT(_032_),
    .SUM(_033_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _296_ (
    .A(\UART_RX.bit_index[2] ),
    .B(_031_),
    .COUT(_034_),
    .SUM(_152_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _297_ (
    .A(\UART_TX.bit_index[2] ),
    .B(_150_),
    .COUT(_035_),
    .SUM(_036_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _298_ (
    .A(_037_),
    .B(_038_),
    .COUT(_039_),
    .SUM(_040_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _299_ (
    .A(_037_),
    .B(\UART_RX.bit_index[1] ),
    .COUT(_041_),
    .SUM(_153_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _300_ (
    .A(\UART_RX.bit_index[0] ),
    .B(_038_),
    .COUT(_042_),
    .SUM(_154_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _301_ (
    .A(\UART_RX.bit_index[0] ),
    .B(\UART_RX.bit_index[1] ),
    .COUT(_031_),
    .SUM(_155_)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.baud_tick$_DFF_PN0_  (
    .CLK(clk),
    .D(_009_),
    .Q(\BAUD_GEN.baud_tick ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[0]$_DFF_PN0_  (
    .CLK(clk),
    .D(_010_),
    .Q(\BAUD_GEN.count[0] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[10]$_DFF_PN0_  (
    .CLK(clk),
    .D(_011_),
    .Q(\BAUD_GEN.count[10] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[11]$_DFF_PN0_  (
    .CLK(clk),
    .D(_012_),
    .Q(\BAUD_GEN.count[11] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[12]$_DFF_PN0_  (
    .CLK(clk),
    .D(_013_),
    .Q(\BAUD_GEN.count[12] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[13]$_DFF_PN0_  (
    .CLK(clk),
    .D(_014_),
    .Q(\BAUD_GEN.count[13] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[1]$_DFF_PN0_  (
    .CLK(clk),
    .D(_015_),
    .Q(\BAUD_GEN.count[1] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[2]$_DFF_PN0_  (
    .CLK(clk),
    .D(_016_),
    .Q(\BAUD_GEN.count[2] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[3]$_DFF_PN0_  (
    .CLK(clk),
    .D(_017_),
    .Q(\BAUD_GEN.count[3] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[4]$_DFF_PN0_  (
    .CLK(clk),
    .D(_018_),
    .Q(\BAUD_GEN.count[4] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[5]$_DFF_PN0_  (
    .CLK(clk),
    .D(_019_),
    .Q(\BAUD_GEN.count[5] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[6]$_DFF_PN0_  (
    .CLK(clk),
    .D(_020_),
    .Q(\BAUD_GEN.count[6] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[7]$_DFF_PN0_  (
    .CLK(clk),
    .D(_021_),
    .Q(\BAUD_GEN.count[7] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[8]$_DFF_PN0_  (
    .CLK(clk),
    .D(_022_),
    .Q(\BAUD_GEN.count[8] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.count[9]$_DFF_PN0_  (
    .CLK(clk),
    .D(_023_),
    .Q(\BAUD_GEN.count[9] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/baud_gen.v:10.1-37.4" *)
  sky130_fd_sc_hd__dfrtp_1 \BAUD_GEN.half_baud$_DFF_PN0_  (
    .CLK(clk),
    .D(_024_),
    .Q(\BAUD_GEN.half_baud ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.bit_index[0]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_043_),
    .Q(\UART_RX.bit_index[0] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.bit_index[1]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_059_),
    .Q(\UART_RX.bit_index[1] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.bit_index[2]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_051_),
    .Q(\UART_RX.bit_index[2] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.data[0]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_054_),
    .Q(rx_data[0]),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.data[1]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_049_),
    .Q(rx_data[1]),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.data[2]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_048_),
    .Q(rx_data[2]),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.data[3]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_047_),
    .Q(rx_data[3]),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.data[4]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_046_),
    .Q(rx_data[4]),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.data[5]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_045_),
    .Q(rx_data[5]),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.data[6]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_044_),
    .Q(rx_data[6]),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.data[7]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_056_),
    .Q(rx_data[7]),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.first_tick$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_052_),
    .Q(\UART_RX.first_tick ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:44.1-126.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.rx_done$_DFF_PN0_  (
    .CLK(clk),
    .D(_025_),
    .Q(rx_done),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:35.1-42.4" *)
  sky130_fd_sc_hd__dfstp_2 \UART_RX.rx_prev$_DFF_PN1_  (
    .CLK(clk),
    .D(\UART_RX.rx_sync2 ),
    .Q(\UART_RX.rx_prev ),
    .SET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:21.1-33.4" *)
  sky130_fd_sc_hd__dfstp_2 \UART_RX.rx_sync1$_DFF_PN1_  (
    .CLK(clk),
    .D(\UART_RX.rx ),
    .Q(\UART_RX.rx_sync1 ),
    .SET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_rx.v:21.1-33.4" *)
  sky130_fd_sc_hd__dfstp_2 \UART_RX.rx_sync2$_DFF_PN1_  (
    .CLK(clk),
    .D(\UART_RX.rx_sync1 ),
    .Q(\UART_RX.rx_sync2 ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 \UART_RX.state[0]$_DFF_PN1_  (
    .CLK(clk),
    .D(_004_),
    .Q(\UART_RX.state[0] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.state[1]$_DFF_PN0_  (
    .CLK(clk),
    .D(_005_),
    .Q(\UART_RX.state[1] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.state[2]$_DFF_PN0_  (
    .CLK(clk),
    .D(_006_),
    .Q(\UART_RX.state[2] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \UART_RX.state[3]$_DFF_PN0_  (
    .CLK(clk),
    .D(_007_),
    .Q(\UART_RX.state[3] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_TX.bit_index[0]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_058_),
    .Q(\UART_TX.bit_index[0] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_TX.bit_index[1]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_057_),
    .Q(\UART_TX.bit_index[1] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_TX.bit_index[2]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_050_),
    .Q(\UART_TX.bit_index[2] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__edfxtp_1 \UART_TX.data_reg[0]$_DFFE_PP_  (
    .CLK(clk),
    .D(tx_data[0]),
    .DE(_008_),
    .Q(\UART_TX.data_reg[0] )
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__edfxtp_1 \UART_TX.data_reg[1]$_DFFE_PP_  (
    .CLK(clk),
    .D(tx_data[1]),
    .DE(_008_),
    .Q(\UART_TX.data_reg[1] )
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__edfxtp_1 \UART_TX.data_reg[2]$_DFFE_PP_  (
    .CLK(clk),
    .D(tx_data[2]),
    .DE(_008_),
    .Q(\UART_TX.data_reg[2] )
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__edfxtp_1 \UART_TX.data_reg[3]$_DFFE_PP_  (
    .CLK(clk),
    .D(tx_data[3]),
    .DE(_008_),
    .Q(\UART_TX.data_reg[3] )
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__edfxtp_1 \UART_TX.data_reg[4]$_DFFE_PP_  (
    .CLK(clk),
    .D(tx_data[4]),
    .DE(_008_),
    .Q(\UART_TX.data_reg[4] )
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__edfxtp_1 \UART_TX.data_reg[5]$_DFFE_PP_  (
    .CLK(clk),
    .D(tx_data[5]),
    .DE(_008_),
    .Q(\UART_TX.data_reg[5] )
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__edfxtp_1 \UART_TX.data_reg[6]$_DFFE_PP_  (
    .CLK(clk),
    .D(tx_data[6]),
    .DE(_008_),
    .Q(\UART_TX.data_reg[6] )
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__edfxtp_1 \UART_TX.data_reg[7]$_DFFE_PP_  (
    .CLK(clk),
    .D(tx_data[7]),
    .DE(_008_),
    .Q(\UART_TX.data_reg[7] )
  );
  sky130_fd_sc_hd__dfstp_2 \UART_TX.state[0]$_DFF_PN1_  (
    .CLK(clk),
    .D(_000_),
    .Q(\UART_TX.state[0] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \UART_TX.state[1]$_DFF_PN0_  (
    .CLK(clk),
    .D(_001_),
    .Q(\UART_TX.state[1] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \UART_TX.state[2]$_DFF_PN0_  (
    .CLK(clk),
    .D(_002_),
    .Q(\UART_TX.state[2] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \UART_TX.state[3]$_DFF_PN0_  (
    .CLK(clk),
    .D(_003_),
    .Q(\UART_TX.state[3] ),
    .RESET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__dfstp_2 \UART_TX.tx$_DFFE_PN1P_  (
    .CLK(clk),
    .D(_055_),
    .Q(\UART_RX.rx ),
    .SET_B(rst_n)
  );
  (* src = "/OpenROAD-flow-scripts/flow/designs/sky130hd/uart/rtl/uart_tx.v:18.1-68.4" *)
  sky130_fd_sc_hd__dfrtp_1 \UART_TX.tx_busy$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_053_),
    .Q(tx_busy),
    .RESET_B(rst_n)
  );
endmodule
